version: "3"
services:
  nginx:
    image: registry.soon.build/stand-ups-recorder:latest
    restart: on-failure
    # makes nginx container aware of web container. name_in_compose:name_in_web
    links:
      - web:web
    ports:
    # external:internal
    - "3000:80"
  web:
    # replace username/repo:tag with your name and image details
    image: registry.soon.build/stand-ups-backend:latest
    restart: on-failure
    environment:
      - DB_HOST=db
      - DB_NAME=stand-ups
      - ROOT=/api
    # wait until db container is ready
    depends_on:
      - db
    # makes web container aware of db container name_in_compose:name_in_web
    links:
      - db:db
    volumes:
      - ./data:/app/data
    # Overrides start command in Dockerfile
    command: sh -c './wait-for db:5432 -- npm start'
  db:
    image: postgres:9.6
    restart: on-failure
    volumes:
      - ./.data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=stand-ups
      - PGDATA=/var/lib/postgresql/data