FORMAT: 1A

# Stand-up Visualisation Backend

A simple Express Web API for the storage and serving of data from SOON_'s daily morning stand-ups.

# Group Staff Members

Resources related to Staff Members in the API.

## Staff Members Collection [/staff-members{?sort,role,firstName}]

### List All Staff Members [GET]

+ Parameters

    + role: `developer` (string, optional) - Filter by role.
        + Default: null
    + firstName: `fred` (string, optional) - Filter by first name.
        + Default: null
    + sort: `firstName:asc` (string, optional)
        Sort staff members by supported parameters
        + Default: `firstName:asc`
        + Members
            + `firstName:asc`
            + `firstName:desc`
            + `lastName:asc`
            + `lastName:desc`
            + `role:asc`
            + `role:desc`

+ Request (application/json; charset=utf-8)

    + Headers

            Accept: application/json

+ Response 200 (application/json)

        {
            "_embedded": {
                "staffMembers": [
                    {
                        "ID": "bf4b3b30-792c-11e7-9e1d-b10f7e8a2b0a",
                        "firstName": "foo",
                        "lastName": "bar",
                        "fullName": "foo bar",
                        "role": "developer",
                        "_links": {
                            "self": {
                                "href": "/v1/staff-members/bf4b3b30-792c-11e7-9e1d-b10f7e8a2b0a"
                            }
                        }
                    }
                ]
            },
            "_links":{
                "self": {
                    "href": "/staff-members"
                }
            }
        }

### Create a Staff Member [POST]

You may create a new Staff Member with this action. It takes a JSON object
containing a role and name information about the new Member.

+ firstName (string)
+ lastName (string)
+ role (string) - For example Designer, Developer or Producer.

+ Request (application/json)

        {
            "firstName": "Foo",
            "lastName": "Bar",
            "role": "Foo"
        }

+ Response 201 (application/json)

    + Body

            {
                "ID": "bf4b3b30-792c-11e7-9e1d-b10f7e8a2b0a",
                "firstName": "foo",
                "lastName": "bar",
                "fullName": "foo bar",
                "role": "developer",
                "_links": {
                    "self": {
                        "href": "/v1/staff-members/bf4b3b30-792c-11e7-9e1d-b10f7e8a2b0a"
                    }
                }
            }

+ Request (application/json)

        {
            "firstName": "Foo",
            "lastName": "Bar"
        }

+ Response 500 (application/json)

    + Body

            {
                "name": "SequelizeValidationError",
                "errors": [
                    {
                        "message": "role cannot be null",
                        "type": "notNull Violation",
                        "path": "role",
                        "value": null
                    }
                ]
            }

## Staff Member [/staff-members/{id}]

Manage a specific Staff Member's state using this resource.

+ Parameters
    + id: `bf4b3b30-792c-11e7-9e1d-b10f7e8a2b0a` (string, required) - The Staff Member UUID

### Get specific Staff Member [GET]

+ Request (application/json; charset=utf-8)

    + Headers

            Accept: application/json

+ Response 200 (application/json)

            {
                "ID": "bf4b3b30-792c-11e7-9e1d-b10f7e8a2b0a",
                "firstName": "foo",
                "lastName": "bar",
                "fullName": "foo bar",
                "role": "developer",
                "_links": {
                    "self": {
                        "href": "/v1/staff-members/bf4b3b30-792c-11e7-9e1d-b10f7e8a2b0a"
                    }
                }
            }

### Update Staff Member [PUT]

+ Request (application/json; charset=utf-8)

    + Headers

            Accept: application/json

+ Response 200 (application/json)

            {
                "ID": "bf4b3b30-792c-11e7-9e1d-b10f7e8a2b0a",
                "firstName": "foo",
                "lastName": "bar",
                "fullName": "foo bar",
                "role": "developer",
                "_links": {
                    "self": {
                        "href": "/v1/staff-members/bf4b3b30-792c-11e7-9e1d-b10f7e8a2b0a"
                    }
                }
            }

### Delete Staff Member [DELETE]

+ Request (application/json; charset=utf-8)

    + Headers

            Accept: application/json

+ Response 200 (application/json)

            []

# Group Days

Resources related to Days in the API.

## Days Collection [/days{?sort}]

### List All Days [GET]

+ Parameters

    + sort: `date:asc` (string, optional)
        Sort days by supported parameters
        + Default: `date:asc`
        + Members
            + `date:asc`
            + `date:desc`

+ Request (application/json; charset=utf-8)

    + Headers

            Accept: application/json

+ Response 200 (application/json)

        {
            "_embedded": {
                "days": [
                    {
                        "ID": "bf4b3b30-792c-11e7-9e1d-b10f7e8a2b0a",
                        "date": "foo",
                        "_links": {
                            "self": {
                                "href": "/v1/days/bf4b3b30-792c-11e7-9e1d-b10f7e8a2b0a"
                            }
                        }
                    }
                ]
            },
            "_links":{
                "self": {
                    "href": "v1/staff-members"
                }
            }
        }

## Day [/days/{id}]

Access a specific day using this resource.

+ Parameters
    + id: `bf52dc51-792c-11e7-9e1d-b10f7e8a2b0a` (string, required) - The day UUID


### Get specific day [GET]

+ Request (application/json; charset=utf-8)

    + Headers

            Accept: application/json

+ Response 200 (application/json)

        {
            "_links": {
                "self": {
                    "href": "v1/staff/bf52dc51-792c-11e7-9e1d-b10f7e8a2b0a"
                }
            },
            "ID": "bf52dc51-792c-11e7-9e1d-b10f7e8a2b0a",
            "date": "2016-04-11T23:00:00.000Z"
        }

# Group Positions

Resources related to Positions in the API.

## Positions Collection [/positions{?date,staffID}]

### List All Positions [GET]

+ Parameters

    + date: `2016-04-11T23:00:00.000Z` (string, optional) - Filter by date.
        + Default: null
    + staffID: `bf52dc51-792c-11e7-9e1d-b10f7e8a2b0a` (string, optional) - Filter by staff member.
        + Default: null

+ Request (application/json; charset=utf-8)

    + Headers

            Accept: application/json

+ Response 200 (application/json)

        {
            "_links": {
                "self": {
                    "href": "/positions?dayID=bf52dc51-792c-11e7-9e1d-b10f7e8a2b0a"
                }
            },
            "_embedded": {
                "positions": [
                    {
                        "_links": {
                            "self": {
                                "href": "v1/positions/bf618250-792c-11e7-9e1d-b10f7e8a2b0a"
                            }
                        },
                        "ID": "bf618250-792c-11e7-9e1d-b10f7e8a2b0a",
                        "placeIndex": 4,
                        "staffID": "bf4b6241-792c-11e7-9e1d-b10f7e8a2b0a",
                        "dayID": "bf52dc51-792c-11e7-9e1d-b10f7e8a2b0a"
                    }
                ]
            }
        }

## Position [/positions/{id}]

Access a specific position using this resource.

+ Parameters
    + id: `bf52dc51-792c-11e7-9e1d-b10f7e8a2b0a` (string, required) - The position UUID


### Get specific position [GET]

+ Request (application/json; charset=utf-8)

    + Headers

            Accept: application/json

+ Response 200 (application/json)

        {
            "_links": {
                "self": {
                    "href": "v1/positions/bf618250-792c-11e7-9e1d-b10f7e8a2b0a"
                }
            },
            "ID": "bf618250-792c-11e7-9e1d-b10f7e8a2b0a",
            "placeIndex": 4,
            "staffID": "bf4b6241-792c-11e7-9e1d-b10f7e8a2b0a",
            "dayID": "bf52dc51-792c-11e7-9e1d-b10f7e8a2b0a"
        }

# Group Summaries

Resources related to Summaries in the API.

## Summaries Collection [/summaries{?date,staffID}]

### List All Summaries [GET]

+ Parameters

    + date: `2016-04-11T23:00:00.000Z` (string, optional) - Filter by date.
        + Default: null
    + staffID: `bf52dc51-792c-11e7-9e1d-b10f7e8a2b0a` (string, optional) - Filter by staff member.
        + Default: null

+ Request (application/json; charset=utf-8)

    + Headers

            Accept: application/json

+ Response 200 (application/json)

        {
            "_links": {
                "self": {
                    "href": "/positions?dayID=bf52dc51-792c-11e7-9e1d-b10f7e8a2b0a"
                }
            },
            "_embedded": {
                "positions": [
                    {
                        "_links": {
                            "self": {
                                "href": "v1/positions/bf618250-792c-11e7-9e1d-b10f7e8a2b0a"
                            }
                        },
                        "ID": "bf618250-792c-11e7-9e1d-b10f7e8a2b0a",
                        "placeIndex": 4,
                        "staffID": "bf4b6241-792c-11e7-9e1d-b10f7e8a2b0a",
                        "dayID": "bf52dc51-792c-11e7-9e1d-b10f7e8a2b0a"
                    }
                ]
            }
        }

## Summary [/summaries/{id}]

Access a specific position using this resource.

+ Parameters
    + id: `bf52dc51-792c-11e7-9e1d-b10f7e8a2b0a` (string, required) - The summary UUID


### Get specific summary [GET]

+ Request (application/json; charset=utf-8)

    + Headers

            Accept: application/json

+ Response 200 (application/json)

        {
            "_links": {
                "self": {
                    "href": "v1/positions/bf618250-792c-11e7-9e1d-b10f7e8a2b0a"
                }
            },
            "ID": "bf618250-792c-11e7-9e1d-b10f7e8a2b0a",
            "placeIndex": 4,
            "staffID": "bf4b6241-792c-11e7-9e1d-b10f7e8a2b0a",
            "dayID": "bf52dc51-792c-11e7-9e1d-b10f7e8a2b0a"
        }